### ISSUE TITLE
可能是已经被反爬了

### ISSUE THREAD

**Issue by jayli517** [xmhhs/spider-qqzhpt#1]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.qqzhpt.com', port=80): Max retries exceeded with url: /meitu/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fda1b166650>: Failed to establish a new connection: [Errno 110] Connection timed out'))

已经显示这个报错了，无法执行。

**Comment by xmhhs** [comment]
没有哦，现在试了一下仍然可以，你可以拉取一下最新版，加了一些日志的打印

**Comment by xmhhs** [comment]
同时你这个报错可能是你那边的网络原因

**Comment by jayli517** [comment]
非常感谢，我再检查一下网络，因为通过浏览器可以访问，我以为是对方网站对请求方式采取措施导致的。
